### ISSUE TITLE
关于hanshow水墨屏的接线问题

### ISSUE THREAD

**Issue by 18cmbanana** [ieiao/hanshow-2in9-epaper#1]
您好
       我看了您关于汉塑的水墨屏的项目，刚好自己也在弄。想问下您的程序是下载在自带的单片机上的吗，因为我看您的程序的头文件是g2553，但是自带的是g2755，它们不冲突吗。还有一个问题是请问您是怎么接线的。十分期待您的解答，感谢您的分享。

**Comment by ieiao** [comment]
对的，这个测试程序是直接下载在价签自带的单片机里面的。
单片机型号不一样的话应该是电子价签的型号不太一样，我买的这个价签内部是msp430g2553。
接线的话由于我是直接使用的电子价签自带的单片机，所以直接用万用表量了一下内部的连接关系，如果你用自己画的板子或者买的现成的驱动板就照着相应的手册连接就可以。

**Comment by 18cmbanana** [comment]
感谢您的回答，我在学习你的代码是发现，在epd_bus_mod_select()函数中对P3.7置高，请问下P3.7是接的屏幕哪个引脚呢

**Comment by 18cmbanana** [comment]
我在看您发的手册上总线设置好像只要设置BS1一个叫即可

**Comment by ieiao** [comment]
P3.7从代码看没有连接任何墨水屏，我也记不太请为啥要设置它了，可能是随手写了忘记删除了，这个仓库的代码逻辑很混乱，因为我只用这段代码做了逻辑验证，后续使用墨水屏的其他仓库目前因为进度关系还未公开，你就直接忽略掉这个引脚就好了。

至于BS1的话一般都使用4线总线模式，就直接拉低就好，如果你想使用3线总线模式那便将它拉高。
